mysql:
  dns: root:root1234@tcp(127.0.0.1:3306)/gin-im?charset=utf8mb4&parseTime=True&loc=Local

redis:
  protocol: tcp
  host: 127.0.0.1:6379
  password: ""
  DB: 0
  poolSize: 30
  minIdleConnection: 30
  
oos:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAI4G3DN5kdk7jbe9hGfEuc
  accessKeySecret: 7RzUrCyhsH1aAWFLRaAMtsONb3V0RG
  bucket: codeart-oss
  accessAddress: https://codeart-oss.oss-cn-shanghai.aliyuncs.com